name: CI Pipeline

# Déclenche le workflow sur push et pull request sur main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests unitaires
      - name: Run tests
        run: |
          pytest

      # Construire l’image Docker
      - name: Build Docker image
        run: |
          docker build -t flaskapp:latest .

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pousser l’image Docker (uniquement si tests OK)
      - name: Push Docker image
        if: success()
        run: |
          docker tag flaskapp:latest <votre-username>/flaskapp:latest
          docker push <votre-username>/flaskapp:latest

